data:
  filename: D:/Projects/Fastview4Geo/data/Satellites/Sat2.TIF
  stretch: histo_equal
output:
  imgtype: PNG
  filename: D:/Projects/Fastview4Geo/output/simpletest.png
  width: 1800
  height: 1500