data:
  filename: D:/Projects/Fastview4Geo/data/Satellites/Sat7.tif
  stretch: piecewise_equal
output:
  imgtype: PNG
  filename: D:/Projects/Fastview4Geo/output/simpletest.png
  width: 400
  height: 2000