data:
  filename: D:/Projects/Fastview4Geo/data/Satellites/Sat1.TIF
  stretch: linear
output:
  imgtype: PNG
  filename: D:/Projects/Fastview4Geo/output/simpletest.png
  width: 1500
  height: 1500
  band1: 3
  band2: 2
  band3: 1