data:
  filename: D:/Projects/Fastview4Geo/data/Satellites/Sat2.TIF
  stretch: tile_stretch
output:
  imgtype: PNG
  filename: D:/Projects/Fastview4Geo/output/simpletest.png
  width: 1500
  height: 1500