data:
  filename: D:/Projects/Fastview4Geo/data/Satellites/Sat4.tiff
  stretch: histo_equal
output:
  imgtype: PNG
  filename: D:/Projects/Fastview4Geo/output/simpletest.png
  width: 1400
  height: 500
  top: 0.3
  left: 0.2
  bottom: 0.8
  right: 0.8
  band1: 3
  band2: 2
  band3: 1